#!/usr/bin/env python3

from __future__ import annotations

import importlib.util
import io
import json
import stat
import tarfile
import tempfile
import unittest
import warnings
import zipfile
from pathlib import Path


SCRIPT = Path(__file__).with_name("observability-runtime-proof.py")
SPEC = importlib.util.spec_from_file_location("runtime_proof", SCRIPT)
assert SPEC and SPEC.loader
runtime_proof = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(runtime_proof)


def jar(entries: list[tuple[str, bytes]], *, timestamp=(2020, 1, 1, 0, 0, 0), compression=zipfile.ZIP_STORED) -> bytes:
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=compression) as archive:
        for name, content in entries:
            info = zipfile.ZipInfo(name, timestamp)
            info.compress_type = compression
            archive.writestr(info, content)
    return output.getvalue()


def base_entries() -> list[dict]:
    app_jar = jar([("b/B.class", b"B"), ("a/A.class", b"A")])
    validation_jar = jar([("fixture/Main.class", b"fixture")])
    return [
        {"name": "./", "type": "dir"},
        {"name": "dev", "type": "dir"},
        {"name": "proc", "type": "dir"},
        {"name": "sys", "type": "dir"},
        {"name": "etc/release", "data": b"temurin"},
        {"name": "lib/libc.so", "data": b"libc"},
        {"name": "opt/java/bin/java", "data": b"jre"},
        {"name": "app/bin/server", "data": b"script"},
        {"name": "app/application.conf", "data": b"config"},
        {"name": "app/lib/server.jar", "data": app_jar},
        {"name": "app/validation.jar", "data": validation_jar},
        {"name": "app/current.conf", "type": "symlink", "target": "application.conf"},
        {"name": ".dockerenv", "data": b"generated"},
        {"name": "etc/hostname", "data": b"container"},
        {"name": "etc/hosts", "data": b"hosts"},
        {"name": "etc/resolv.conf", "data": b"resolver"},
    ]


def write_tar(path: Path, entries: list[dict], *, mtime: int = 1) -> None:
    with tarfile.open(path, "w") as archive:
        for item in entries:
            info = tarfile.TarInfo(item["name"])
            info.mode = item.get("mode", 0o755 if item.get("type") == "dir" else 0o644)
            info.uid = item.get("uid", 1000)
            info.gid = item.get("gid", 1000)
            info.mtime = item.get("mtime", mtime)
            kind = item.get("type", "file")
            if kind == "dir":
                info.type = tarfile.DIRTYPE
                archive.addfile(info)
            elif kind == "symlink":
                info.type = tarfile.SYMTYPE
                info.linkname = item["target"]
                archive.addfile(info)
            elif kind == "hardlink":
                info.type = tarfile.LNKTYPE
                info.linkname = item["target"]
                archive.addfile(info)
            elif kind == "char":
                info.type = tarfile.CHRTYPE
                archive.addfile(info)
            else:
                data = item["data"]
                info.size = len(data)
                archive.addfile(info, io.BytesIO(data))


class RuntimeProofTest(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.config = self.root / "config.json"
        self.dockerfile = self.root / "Dockerfile"
        self.config.write_text(json.dumps({
            "Entrypoint": ["java", "-cp", "/app/lib/*:/app/validation.jar", "Main"],
            "Cmd": None,
            "User": "app",
            "WorkingDir": "/app",
            "Env": ["PATH=/opt/java/bin", "VALIDATION=true"],
        }))
        self.dockerfile.write_text("FROM base\nCOPY validation.jar /app/validation.jar\n")

    def tearDown(self) -> None:
        self.temp.cleanup()

    def rootfs_hash(self, entries: list[dict], *, name="rootfs.tar", mtime=1) -> str:
        path = self.root / name
        write_tar(path, entries, mtime=mtime)
        return runtime_proof.rootfs_manifest(path)[0]

    def test_archive_metadata_order_and_fixed_generated_files_are_invariant(self) -> None:
        entries = base_entries()
        baseline = self.rootfs_hash(entries)
        changed = list(reversed(entries))
        for item in changed:
            if item["name"] in runtime_proof.EXCLUDED_PATHS:
                item = item.copy()
                item["data"] = b"different generated bytes"
                changed[changed.index(next(v for v in changed if v["name"] == item["name"]))] = item
        self.assertEqual(baseline, self.rootfs_hash(changed, name="changed.tar", mtime=999999))

    def test_zip_order_timestamp_and_compression_are_invariant(self) -> None:
        entries = base_entries()
        baseline = self.rootfs_hash(entries)
        replacement = jar(
            [("a/A.class", b"A"), ("b/B.class", b"B")],
            timestamp=(2025, 5, 5, 5, 5, 4),
            compression=zipfile.ZIP_DEFLATED,
        )
        changed = [dict(item, data=replacement) if item["name"] == "app/lib/server.jar" else item for item in entries]
        self.assertEqual(baseline, self.rootfs_hash(changed, name="zip.tar"))

    def test_runtime_content_metadata_and_links_change_hash(self) -> None:
        baseline_entries = base_entries()
        baseline = self.rootfs_hash(baseline_entries)
        cases = [
            ("etc/release", "data", b"other-os"),
            ("lib/libc.so", "data", b"new-libc"),
            ("opt/java/bin/java", "data", b"new-jre"),
            ("app/bin/server", "data", b"new-script"),
            ("app/application.conf", "data", b"new-config"),
            ("app/lib/server.jar", "data", jar([("a/A.class", b"changed")])),
            ("app/current.conf", "target", "/app/other.conf"),
            ("app/bin/server", "mode", 0o755),
            ("app/bin/server", "uid", 2000),
            ("app/bin/server", "gid", 2000),
        ]
        for index, (path, key, value) in enumerate(cases):
            with self.subTest(path=path, key=key):
                changed = [dict(item) for item in baseline_entries]
                next(item for item in changed if item["name"] == path)[key] = value
                self.assertNotEqual(baseline, self.rootfs_hash(changed, name=f"sensitive-{index}.tar"))

    def test_unlisted_etc_changes_hash(self) -> None:
        entries = base_entries()
        baseline = self.rootfs_hash(entries)
        changed = [dict(item, data=b"changed") if item["name"] == "etc/release" else item for item in entries]
        self.assertNotEqual(baseline, self.rootfs_hash(changed, name="etc.tar"))

    def test_config_and_dockerfile_change_applicability(self) -> None:
        rootfs = self.root / "rootfs.tar"
        write_tar(rootfs, base_entries())
        baseline_config = json.loads(self.config.read_text())
        baseline = runtime_proof.build_manifest(rootfs, self.config, self.dockerfile)["applicabilitySha256"]
        changes = {
            "Entrypoint": ["java", "OtherMain"],
            "Cmd": ["argument"],
            "User": "other",
            "WorkingDir": "/other",
            "Env": baseline_config["Env"] + ["EXTRA=value"],
        }
        for key, value in changes.items():
            with self.subTest(config=key):
                self.config.write_text(json.dumps(baseline_config | {key: value}))
                self.assertNotEqual(
                    baseline,
                    runtime_proof.build_manifest(rootfs, self.config, self.dockerfile)["applicabilitySha256"],
                )
        self.config.write_text(json.dumps(baseline_config))
        self.dockerfile.write_text(self.dockerfile.read_text() + "ENV EXTRA=true\n")
        self.assertNotEqual(
            baseline,
            runtime_proof.build_manifest(rootfs, self.config, self.dockerfile)["applicabilitySha256"],
        )

    def test_invalid_tar_entries_fail_closed(self) -> None:
        cases = [
            [{"name": "same", "data": b"a"}, {"name": "same", "data": b"b"}],
            [{"name": "../escape", "data": b"x"}],
            [{"name": "/absolute", "data": b"x"}],
            [{"name": "proc/status", "data": b"x"}],
            [{"name": "sys/kernel", "type": "dir"}],
            [{"name": "dev/null", "type": "char"}],
            [{"name": "device", "type": "char"}],
            [{"name": "app/link", "type": "symlink", "target": "../../host"}],
            [{"name": "app/file", "type": "hardlink", "target": "missing"}],
            [{"name": "app/file", "type": "hardlink", "target": "/app/target"}],
        ]
        for index, entries in enumerate(cases):
            with self.subTest(index=index):
                path = self.root / f"invalid-{index}.tar"
                write_tar(path, entries)
                with self.assertRaises(runtime_proof.ManifestError):
                    runtime_proof.rootfs_manifest(path)

    def test_valid_absolute_symlink_and_hardlink_are_canonical(self) -> None:
        entries = [
            {"name": "app/file", "data": b"content"},
            {"name": "app/symlink", "type": "symlink", "target": "/app/file"},
            {"name": "app/hardlink", "type": "hardlink", "target": "app/file"},
        ]
        _, manifest = runtime_proof.rootfs_manifest(self._tar("links.tar", entries))
        records = {record["path"]: record for record in manifest}
        self.assertEqual("/app/file", records["app/symlink"]["target"])
        self.assertEqual("app/file", records["app/symlink"]["resolvedTarget"])
        self.assertEqual("app/file", records["app/hardlink"]["target"])
        self.assertEqual("app/file", records["app/hardlink"]["resolvedTarget"])

    def test_duplicate_excluded_path_and_changed_raw_symlink_target_are_detected(self) -> None:
        duplicate = [
            {"name": ".dockerenv", "data": b"one"},
            {"name": ".dockerenv", "data": b"two"},
        ]
        with self.assertRaises(runtime_proof.ManifestError):
            runtime_proof.rootfs_manifest(self._tar("duplicate-excluded.tar", duplicate))

        direct = [{"name": "app/link", "type": "symlink", "target": "/app/file"}]
        equivalent = [{"name": "app/link", "type": "symlink", "target": "/app/dir/../file"}]
        self.assertNotEqual(
            self.rootfs_hash(direct, name="direct-link.tar"),
            self.rootfs_hash(equivalent, name="equivalent-link.tar"),
        )

    def test_invalid_zip_paths_duplicates_and_links_fail_closed(self) -> None:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            duplicate = jar([("same", b"a"), ("same", b"b")])
        traversal = jar([("../escape", b"x")])
        linked = io.BytesIO()
        with zipfile.ZipFile(linked, "w") as archive:
            info = zipfile.ZipInfo("linked")
            info.create_system = 3
            info.external_attr = (stat.S_IFLNK | 0o777) << 16
            archive.writestr(info, "target")
        for index, invalid in enumerate((duplicate, traversal, linked.getvalue())):
            entries = [{"name": "app/validation.jar", "data": invalid}]
            with self.subTest(index=index):
                with self.assertRaises(runtime_proof.ManifestError):
                    runtime_proof.rootfs_manifest(self._tar(f"bad-zip-{index}.tar", entries))

    def _tar(self, name: str, entries: list[dict]) -> Path:
        path = self.root / name
        write_tar(path, entries)
        return path


if __name__ == "__main__":
    unittest.main()
